version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd src
      - npm install
      - cd ..
  build:
    commands:
      - sam build --template template.yaml --build-dir .aws-sam/build
      - sam package --s3-bucket $S3_BUCKET --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml
